baseURL = ''
languageCode = 'en-us'
title = 'Sinjoy Saha'
theme = "hugo-academicpages"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup.tableOfContents]
    startLevel = 1
    endLevel = 6

[[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 10
    
[[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 20

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/assets/Sinjoy_Saha_CV.pdf"
  target = "_blank"
  weight = 50


[params]
  follow_label = "Follow"
  powered_by = "Powered by"

  [params.author]
    name = "Sinjoy Saha"
    avatar = "profilePic.jpg"
    bio = "Senior Research Engineer @ MI, Siemens Healthineers"
    [params.author.details]
      [[params.author.details.list]]
      class = "location"
      icon = "fa-map-marker"
      title = "Kolkata, WB, India"

    [params.author.contact]
      [[params.author.contact.list]]
      class = "email"
      icon = "fa-envelope"
      url = "mailto:sinjoysaha555@gmail.com"
      title = "Email"

    [params.author.social]
      [[params.author.social.list]]
      class = "googelscholar"
      icon = "fas fa-graduation-cap"
      url = "https://scholar.google.com/citations?user=xNXqCc0AAAAJ&hl=en"
      title = "Google Scholar"

      [[params.author.social.list]]
      class = "linkedin"
      icon = "fab fa-linkedin"
      url = "https://linkedin.com/in/sinjoysaha"
      title = "LinkedIn"

      [[params.author.social.list]]
      class = "twitter"
      icon = "fab fa-twitter-square"
      url = "https://twitter.com/sinjoysaha"
      title = "Twitter"

      [[params.author.social.list]]
      class = "github"
      icon = "fab fa-github"
      url = "https://github.com/sinjoysaha"
      title = "GitHub"

    
      
